services:
  synapse:
    image: matrixdotorg/synapse:latest
    container_name: synapse
    restart: unless-stopped
    volumes:
      - /mnt/Share/Element/synapse-data:/data
    environment:
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
    ports:
      - "8008:8008"
    extra_hosts:
      - "leonet.site:host-gateway"

  element:
    image: vectorim/element-web:latest
    container_name: element
    restart: unless-stopped
    volumes:
      - /mnt/Share/Element/element-config.json:/app/config.json
    ports:
      - "8081:80"

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=synapse
      - POSTGRES_USER=synapse
      - POSTGRES_PASSWORD=${PG_PASS}
    volumes:
      - /mnt/Share/Element/postgres-data:/var/lib/postgresql/data
  
